[PULL REQUEST] Fix awaitElement helper
Universal-Bypass-Renewed/Universal-Bypass pull request #1273
Opened 2023-12-07 00:58 UTC by kiraio-moe

- [X] I made sure there are no unnecessary changes in the code;
- [X] Tested on Chromium (Includes Opera, Brave, Vivaldi, Edge, etc);
- [X] Tested on Firefox.

2023-12-30 14:53 UTC, NotAProton requested changes
Sorry for the delay in reviewing

2023-12-30 14:53 UTC, NotAProton commented on src/helpers/dom.js
> +        resolve(el)
Make it promise-only
```suggestion
 * @returns {Promise<any>} A promise that resolves with the element.
 */
export function watchForElement (selector) {
  return new Promise(resolve => {
    const element = document.querySelector(selector)
    if (element) {
      console.log(`[FastForward] Element found: ${element} | Selector: ${selector}`)
      resolve(element)
      return
    }

    const observer = new MutationObserver(() => {
      Array.from(document.querySelectorAll(selector)).forEach(el => {
        console.log(`[FastForward] Element found: ${el} | Selector: ${selector}`)
        resolve(el)
```

2023-12-31 00:21 UTC, kiraio-moe commented
Sure, I'll update it on Sunday.

Pada Sab, 30 Des 2023 21.53, NotAProton ***@***.***> menulis:

> ***@***.**** requested changes on this pull request.
>
> Sorry for the delay in reviewing
> ------------------------------
>
> In src/helpers/dom.js
> <https://github.com/FastForwardTeam/FastForward/pull/1273#discussion_r1438621339>
> :
>
> > + * @param {function} f - The function to call.
> + */
> +export function watchForElement (selector, callback) {
> +  return new Promise(resolve => {
> +    const element = document.querySelector(selector)
> +    if (element) {
> +      console.log(`[FastForward] Element found: ${element} | Selector: ${selector}`)
> +      callback(element)
> +      resolve(element)
> +      return
> +    }
> +
> +    const observer = new MutationObserver(() => {
> +      Array.from(document.querySelectorAll(selector)).forEach(el => {
> +        console.log(`[FastForward] Element found: ${el} | Selector: ${selector}`)
> +        callback(el)
> +        resolve(el)
>
> Make it promise-only
> ⬇️ Suggested change
>
> - * @param {function} f - The function to call.
> - */
> -export function watchForElement (selector, callback) {
> -  return new Promise(resolve => {
> -    const element = document.querySelector(selector)
> -    if (element) {
> -      console.log(`[FastForward] Element found: ${element} | Selector: ${selector}`)
> -      callback(element)
> -      resolve(element)
> -      return
> -    }
> -
> -    const observer = new MutationObserver(() => {
> -      Array.from(document.querySelectorAll(selector)).forEach(el => {
> -        console.log(`[FastForward] Element found: ${el} | Selector: ${selector}`)
> -        callback(el)
> -        resolve(el)
> + * @returns {Promise<any>} A promise that resolves with the element.
> + */
> +export function watchForElement (selector) {
> +  return new Promise(resolve => {
> +    const element = document.querySelector(selector)
> +    if (element) {
> +      console.log(`[FastForward] Element found: ${element} | Selector: ${selector}`)
> +      resolve(element)
> +      return
> +    }
> +
> +    const observer = new MutationObserver(() => {
> +      Array.from(document.querySelectorAll(selector)).forEach(el => {
> +        console.log(`[FastForward] Element found: ${el} | Selector: ${selector}`)
> +        resolve(el)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FastForwardTeam/FastForward/pull/1273#pullrequestreview-1799564135>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AN4W4LSETT4ITCUYEUAB4ETYMATGRAVCNFSM6AAAAABAKIAB5WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOJZGU3DIMJTGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-02 06:23 UTC, kiraio-moe commented on src/helpers/dom.js
> +        resolve(el)
Ok, done.

2024-01-03 09:31 UTC, NotAProton approved these changes

2024-01-05 05:59 UTC, merged