Update injection_script.js
Universal-Bypass-Renewed/Universal-Bypass pull request #294
Opened 2022-01-01 19:27 UTC by shalabio

Bypasses for some sites requiring several "next" clicks like forexmab.com, forexlap.com, forex-articles.com.
Tested and working fine.

<details> <summary>NOTICE</summary>
I dedicate any and all copyright interest in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.
</details>

Fixes: Link to issue

Added 3 bypasses to sites which require one to click a link at the top of page to send us to bottom and click another NEXT link. These 3 sites are often chained together.
Example: http://linkjust.com/ackNeTSd

- [ X] I made sure there are no unnecessary changes in the code*
- [ X] Tested on Chromium- Browser OS
- [ ] Tested on Firefox

\* indicates required

2022-01-12 20:37 UTC, shalabio commented
So what's next ? who's going to incorporate this patch in the update ? Forgive my ignorance.

2022-01-13 23:58 UTC, lem6ns requested changes

2022-01-13 23:58 UTC, lem6ns commented on src/js/injection_script.js
> +
Please close the function.

2022-01-13 23:58 UTC, lem6ns commented on src/js/injection_script.js
> +
Please close the function.

2022-01-13 23:58 UTC, lem6ns commented on src/js/injection_script.js
> +
Please close the function.

2022-01-16 04:37 UTC, lem6ns approved these changes
Looks good.

2022-01-26 09:29 UTC, merged