add support for linkvertise pastes
Universal-Bypass-Renewed/Universal-Bypass pull request #928
Opened 2023-03-29 20:38 UTC by davidkra230

Fixes (Links to issues fixed by this PR): 
None

Description:
bypasses linkvertise's pasting feature. basically i just added a check for pastes and if it matches it will get the info almost exactly like the url bypass except it copies the paste instead of redirecting.

Test links:
[LinkvertisePaste](https://linkvertise.com/114822/test?o=sharing)
Checklist:

- [x] I made sure there are no unnecessary changes in the code*
- [ ] Tested on Chromium- Browser OS
- [ ] Tested on Firefox

2023-04-02 22:07 UTC, lem6ns requested changes
please fix formatting and see review comments.

2023-04-02 22:07 UTC, lem6ns commented on src/js/injection_script.js
> +			    )
why was formatting changed here?

2023-04-02 22:07 UTC, lem6ns commented on src/js/injection_script.js
> +			)
why was formatting changed here?

2023-04-02 22:07 UTC, lem6ns commented on src/js/injection_script.js
> +				    insertInfoBox("Paste detected, bypassing..")
this line isn't needed, and what if `.target_type` was also not a paste?

2023-04-02 22:07 UTC, lem6ns commented on src/js/injection_script.js
> +				    let pathmap = {
change to `const` instead of `let`

2023-04-02 22:07 UTC, lem6ns commented on src/js/injection_script.js
> +							})
consider making an inner function for creating a serial

2023-04-02 22:07 UTC, lem6ns commented on src/js/injection_script.js
> +								"application/json",
awkward formatting?

2023-04-02 22:07 UTC, lem6ns commented on src/js/injection_script.js
> +							      window.prompt("Copying to clipboard failed!\nThe paste is displayed below. Ctrl+C to copy it.", json?.data.paste)
consider creating a blob text file, then creating an objectURL to redirect/open a new tab to.

2023-04-02 22:07 UTC, lem6ns commented on src/js/injection_script.js
> +					    })
consider making an inner function for creating a serial

2023-04-02 22:14 UTC, davidkra230 commented on src/js/injection_script.js
> +			    )
prettier was used

2023-04-02 22:14 UTC, davidkra230 commented on src/js/injection_script.js
> +			)
prettier was used

2023-04-02 22:15 UTC, davidkra230 commented on src/js/injection_script.js
> +								"application/json",
prettier was used

2023-04-03 00:31 UTC, davidkra230 commented
I have fixed these but, I had deleted the original repository in which I had made the changes and therefore, I need to open a new pull request.

I will close this pull request for now, and I will open a new one with the requested changes.

2023-04-03 00:31 UTC, closed without merging

2023-04-03 00:35 UTC, lem6ns commented
alright