Added a modular system for bypassing different linkvertise content types and added a paste bypass.
Universal-Bypass-Renewed/Universal-Bypass pull request #934
Opened 2023-04-03 01:55 UTC by davidkra230

\#### continuation of #928 and #933, third time's the charm (next time I should really only push when I'm 100% done) ####

Fixes (Links to issues fixed by this PR): 
None

Description:
bypasses linkvertise's pasting feature. basically i just added a check for pastes and if it matches it will get the info almost exactly like the url bypass ~~except it copies the paste instead of redirecting~~ but it redirects to a blob url of the paste text.

Test links:
[LinkvertisePaste](https://linkvertise.com/114822/test?o=sharing)
Checklist:

- [x] I made sure there are no unnecessary changes in the code*
- [x] Tested on Chromium- Browser OS
- [x] Tested on Firefox

2023-04-03 02:03 UTC, lem6ns approved these changes
lgtm

2023-04-03 02:03 UTC, lem6ns commented on src/js/injection_script.js
> +                                                        new Blob([json?.data.paste], { type: "text/plain" })
optional chaining not needed here

2023-04-03 02:03 UTC, lem6ns commented on src/js/injection_script.js
> +                                    link_id:json.data.link.id
add spaces after colons

2023-04-03 02:20 UTC, davidkra230 commented on src/js/injection_script.js
> +                                    link_id:json.data.link.id
I didn't even notice that myself.

2023-04-03 02:23 UTC, davidkra230 commented
I will be fixing anything that the reviewers need me to fix and after I have fixed everything, I will squash the commits into one and it will be ready to ship. (I think)

2023-04-03 17:47 UTC, princessmortix approved these changes

2023-04-03 21:05 UTC, 0xc60f requested changes

2023-04-03 21:05 UTC, ghost commented on src/js/injection_script.js
> +                                return insertInfoBox('Due to copyright reasons we are not bypassing linkvertise stored content (paste, download etc)');
Rename the sentence to "Due to issues with Linkvertise, we are not bypassing content stored on their site (paste, download, etc)" to make it more clear.

2023-04-04 02:06 UTC, 0xc60f requested changes
"Due to legal issues with Linkvertise, we are not bypassing content stored on their site (paste, download, etc)". Can you please change the infobox text to this line?

2023-04-04 02:46 UTC, lem6ns commented
> "Due to legal issues with Linkvertise, we are not bypassing content stored on their site (paste, download, etc)". Can you please change the infobox text to this line?

this doesn't really make sense, no? as this PR bypasses their paste system

2023-04-04 02:47 UTC, 0xc60f commented
> > "Due to legal issues with Linkvertise, we are not bypassing content stored on their site (paste, download, etc)". Can you please change the infobox text to this line?
> 
> this doesn't really make sense, no? as this PR bypasses their paste system

Ah I see, I was under the impression that we were still were not going to bypass content on their site.

2023-04-04 02:48 UTC, 0xc60f approved these changes

2023-04-04 02:50 UTC, merged