Mv3: Remove UIkit and revamp pages with FastForward CSS
Universal-Bypass-Renewed/Universal-Bypass pull request #964
Opened 2023-04-20 07:59 UTC by NotAProton

To test before navigate pages, click on these links with the extension installed:
crowd-bypassed: https://fastforward.team/bypassed?target=https%3A%2F%2Fgoogle.com&crowd=true
before-navigate: https://fastforward.team/bypassed?target=https%3A%2F%2Fgoogle.com

Description:
- Removed UIkit, now the extension uses no external libraries 
- Rewrote options, before-navigate and crowd-bypassed pages using css from the FastForward website
- Copied over CONTRIBUTORS.md from main

Checklist:

- [x] I made sure there are no unnecessary changes in the code*
- [x] Tested on Chromium- Chrome 112 Windows
- [x] Tested on Firefox

2023-04-20 08:25 UTC, AliahX commented
i'll check it out in a minute, just working on another pr rn

2023-04-21 15:54 UTC, NotAProton commented on src/html/base.js
> +            brws.i18n.getMessage(message).replace('%', secondsLeft) + ' ';
That is actually redundant and should have been removed in #921

2023-04-21 20:19 UTC, AliahX commented on src/html/base.js
> +            brws.i18n.getMessage(message).replace('%', secondsLeft) + ' ';
oh oki

2023-04-26 00:11 UTC, AliahX commented
This branch is missing the CONTRIBUTORS.md file that is linked to by the extension.

2023-04-30 11:19 UTC, NotAProton commented
what about mobile responsiveness?
![chrome-extension___ambaeodiomeedcpomkgkkobenfgddedg_html_options html](https://user-images.githubusercontent.com/81463636/235350149-230fcffe-c9fc-41b5-b4ab-127d6b6a6c7a.png)

2023-05-01 11:01 UTC, AliahX commented
I think i have a solution maybe. Do we need the changelog faq and contributors buttons on mobile?

2023-05-01 11:03 UTC, NotAProton commented
I think only 3 people ever clicked on them lol, we can just push them to the bottom

2023-05-02 00:50 UTC, 0xc60f requested changes

2023-05-02 00:50 UTC, ghost commented on CONTRIBUTORS.md
> +- FastForward uses [UIkit](https://getuikit.com/) for its design
Remove these 2 lines, that's the whole point of the PR.

2023-05-06 13:14 UTC, merged