Create pahe.js for pahe.in|ph|me
Universal-Bypass-Renewed/Universal-Bypass pull request #972
Opened 2023-04-24 16:14 UTC by LoSunny

Fixes (Links to issues fixed by this PR): 
None

Description:
Translating from https://github.com/FastForwardTeam/FastForward/blob/472428a5d788e7c8aae519850629aebdb018a1cb/src/js/injection_script.js#L763

Test links:
None

Checklist:
- [x] I made sure there are no unnecessary changes in the code*
- [ ] Tested on Chromium- Browser OS
- [ ] Tested on Firefox

The `npm run build` doesn't work on MacOS, which I don't have Linux or Win machine to test on 🥲
And am I making mv3 bypasses correctly?

2023-04-27 00:56 UTC, 0xc60f commented
You should be running node .\scripts\build.js in the root directory to build it. You need to use forward slashes since you mentioned that you are running MacOS.

2023-04-27 01:33 UTC, 0xc60f requested changes

2023-04-27 01:33 UTC, ghost commented on src/bypasses/pahe.js
> +export default class Lnk extends BypassDefinition {
You should change the class name to match the website name
```suggestion
export default class Pahe extends BypassDefinition {
```

2023-04-27 07:33 UTC, LoSunny commented
> You should be running `node .\scripts\build.js all` in the root directory to build it. You need to use forward slashes since you mentioned that you are running MacOS.

It worked, and the extension was running correctly in both Chrome & Firefox. However I don't have any test link to see if the bypass works or not 😅

2023-04-29 23:49 UTC, 0xc60f approved these changes

2023-04-30 00:15 UTC, 0xc60f requested changes
In my testing, it didn't appear to redirect me to the final destination; can you change it so that it does?

2023-05-01 00:03 UTC, LoSunny commented
I'll see what I can do in my free time, and understand what is the use of `bypassClipboard`

2023-05-01 00:05 UTC, 0xc60f commented
> I'll see what I can do in my free time, and understand what is the use of `bypassClipboard`

bypassClipboard is meant to hold values for later use, but you need to use a function for FF to navigate to the final destination. I think you have the values already needed for the final destination, but it's just a matter of using a function like safelyNavigate.

2023-05-01 08:01 UTC, NotAProton commented
bypassClipboard (which was used to inject custom bypass) has been deprecated. ffclipboard is used to save data temporarily

2023-07-26 22:15 UTC, 0xc60f commented
Closing this pr because I've created a bypass for intercelestial, which is the meat of the site.

2023-07-26 22:15 UTC, closed without merging

2023-07-26 22:31 UTC, LoSunny commented
Thanks for creating one. I'm on vacation and didn't have time to complete it